# Generated by Django 5.0.3 on 2024-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkipmanTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipmanTuru', models.CharField(max_length=50, verbose_name='Ekipman Türü')),
            ],
        ),
    ]
