# Generated by Django 5.0.3 on 2024-03-27 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EkipmanTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipmanTuru', models.CharField(max_length=50, verbose_name='Ekipman Türü')),
            ],
        ),
        migrations.CreateModel(
            name='Konum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipmanKonumu', models.CharField(max_length=50, verbose_name='Ekipmanın Konumu')),
            ],
        ),
        migrations.CreateModel(
            name='Makine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makineAdi', models.CharField(max_length=50, verbose_name='Makine Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Tedarikci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedarikciFirma', models.CharField(max_length=100, verbose_name='Tedarikçi Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Ekipman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipmanAdi', models.CharField(max_length=50, verbose_name='Ekipman Adı')),
                ('ekipmanAciklamasi', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ekipman Açıklaması')),
                ('ekipmanMarkasi', models.CharField(max_length=50, verbose_name='Ekipmanın Markası')),
                ('ekipmanResmi', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ekipmanın Resmi')),
                ('ekipmanVarlikStokMiktari', models.IntegerField(verbose_name='Ekipman Varlık Stoğu')),
                ('arizaliMiktar', models.IntegerField(verbose_name='Arızalı Ekipman Stoğu')),
                ('kullanilanMiktar', models.IntegerField(verbose_name='Aktif Ekipman Stoğu')),
                ('kullanilabilirMiktar', models.IntegerField(verbose_name='Erişilebilir Ekipman Stoğu')),
                ('ekleyenPersonel', models.CharField(max_length=50, verbose_name='Ekleyen Personel')),
                ('eklenmeTarihi', models.DateField(verbose_name='Eklenme Tarihi')),
                ('sonGuncelleyenPersonel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Son Güncelleyen Personel')),
                ('sonGuncellenmeTarihi', models.DateField(blank=True, null=True, verbose_name='Son Güncellenme Tarihi')),
                ('aktiflikDurumu', models.BooleanField(default=True, verbose_name='Aktiflik Durumu')),
                ('ekipmanTuru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekipman.ekipmanturu')),
                ('ekipmanKonumu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekipman.konum')),
                ('iliskiliMakine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ekipman.makine')),
                ('tedarikciFirma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ekipman.tedarikci')),
            ],
        ),
    ]
