# Generated by Django 5.0.3 on 2024-03-27 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipman', '0001_initial'),
        ('kategori', '0001_initial'),
        ('konum', '0001_initial'),
        ('makine', '0001_initial'),
        ('tedarikci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipman',
            name='ekipmanTuru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kategori.ekipmanturu'),
        ),
        migrations.AlterField(
            model_name='ekipman',
            name='ekipmanKonumu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konum.konum'),
        ),
        migrations.AlterField(
            model_name='ekipman',
            name='iliskiliMakine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='makine.makine'),
        ),
        migrations.AlterField(
            model_name='ekipman',
            name='tedarikciFirma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tedarikci.tedarikci'),
        ),
        migrations.DeleteModel(
            name='EkipmanTuru',
        ),
        migrations.DeleteModel(
            name='Konum',
        ),
        migrations.DeleteModel(
            name='Makine',
        ),
        migrations.DeleteModel(
            name='Tedarikci',
        ),
    ]
