# Generated by Django 5.0.3 on 2024-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekipman', '0003_hatatalep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatatalep',
            name='aciklama',
            field=models.CharField(max_length=500, verbose_name='Açıklama'),
        ),
    ]
